[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
directory=/app
autostart=true
autorestart=true
startsecs=2
startretries=10
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/uvicorn.err.log
stdout_logfile=/var/log/supervisor/uvicorn.out.log
